Added the `patchwork-access-modifications` module and publicized `Min…
PatchworkMC/patchwork-api pull request #190
Opened 2020-09-15 12:45 UTC by YTG1234

…ecraftClient#textureManager`.

Just saw this on #125 so I decided to do it.

2020-09-16 12:43 UTC, YTG1234 commented
Maybe we could also move all Forge's access modifications that are already in Patchwork to this new module, idk how it's going to be possible to "load" the access widener when developing other modules. Any thoughts?

2020-09-16 13:29 UTC, famous1622 requested changes

2020-09-16 13:29 UTC, famous1622 commented on patchwork-access-modifications/build.gradle
> +version = getSubprojectVersion(project, "0.0.0")
The version should start at 0.1.0

2020-09-16 13:29 UTC, famous1622 commented on settings.gradle
> +include 'patchwork-access-modifications'
These should be in alphabetical order.

2020-09-16 14:58 UTC, YTG1234 commented on settings.gradle
> +include 'patchwork-access-modifications'
Should be fixed now

2020-09-16 14:58 UTC, YTG1234 commented on patchwork-access-modifications/build.gradle
> +version = getSubprojectVersion(project, "0.0.0")
Should be fixed now

2020-09-16 15:24 UTC, TheGlitch76 commented
Moving access wideners to their own module isn't the right solution yet because nobody has made a jar processor to make access wideners transitive.
I think instead of its own module, for now this should either be in an appropriate module that already exists (Check the Forge source code and see if it's used anywhere), or failing that dropped in `patchwork-fml`.

2020-09-16 15:32 UTC, YTG1234 commented
I think it may be used in the forge `CloudRenderer`: `mc.textureManager.bindTexture(texture);`. I'm not sure

2020-09-16 15:34 UTC, YTG1234 commented
Yep. It's only used in `CloudRenderer`

2020-09-16 15:36 UTC, YTG1234 commented
I will put it in the FML module

2020-09-16 15:42 UTC, YTG1234 commented
Moved it to the FML module for now. I didn't bump the version - as the commit msg says.

2020-09-16 15:46 UTC, YTG1234 commented
Turns out I put a `/`. Fixed it to a `.`, it should run now.

2020-09-17 06:40 UTC, YTG1234 commented
Updated the title so it's less confusing

2020-09-17 07:18 UTC, YTG1234 commented
@famous1622 I changed things up a little, can you review again?

2020-09-17 18:01 UTC, rikka0w0 commented
> Moving access wideners to their own module isn't the right solution yet because nobody has made a jar processor to make access wideners transitive.
> I think instead of its own module, for now this should either be in an appropriate module that already exists (Check the Forge source code and see if it's used anywhere), or failing that dropped in `patchwork-fml`.

I think in the future the rendering stuff should have their own package. But for now I would agree that this aw should be in `patchwork-fml`. Sometimes `mc.textureManager` is used by mods in their tileentity render and entity render, I don't there is a direct reference to that field in Forge.

2020-09-17 19:30 UTC, YTG1234 commented
It's interesting that in most places Forge uses `getTextureManager()`, so I don't understand why the field has been made public

2020-09-17 19:32 UTC, famous1622 commented
Was probably public forever ago and they don't want to break mods

2020-09-19 14:58 UTC, YTG1234 commented
Test ![](https://cdn.discordapp.com/emojis/552977803633623040.png?v=1)

2020-09-26 17:11 UTC, TheGlitch76 approved these changes
LGTM!

2020-09-26 17:11 UTC, merged

2020-09-26 17:13 UTC, YTG1234 commented
> Was probably public forever ago and they don't want to break mods

I thought Forge was the opposite of backwards-compatibility

2020-09-26 17:19 UTC, TheGlitch76 commented
Forge is more than just Lex and all of them do try to maintain back-compat for some things.